// src/routes/admin/create-student.svelte
<script>
import { Axios } from "../../services/axios";

  let name = '';
  let email = '';

  async function submit() {
    await Axios.$post('students', {
      name, email
    })
  }
</script>

<div>
  <form on:submit|preventDefault={submit}>
    <input bind:value={name}>
    <input bind:value={email}>
    <button type="submit">
      Create
    </button>
  </form>
</div>

// src/pages/admin/create-student.vue
<template>
  <div>
    <input v-model="name">
    <input v-model="email">
    <button @click="submit">
      Create
    </button>
  </div>
</template>

<script>
export default {
  data() {
    return {
      name: '',
      email: ''
    }
  },
  methods: {
    async submit() {
      await this.$axios.$post('students', {
        name: this.name, email: this.email
      })
    }
  }
}
</script>

<style>

</style>
